#!/bin/bash

dirname=`dirname $0`

make -s crt0.o
make -s libc.a

gcc -nostdlib -ffreestanding -fno-stack-protector -Wall -Wextra -fno-builtin\
 -isystem $dirname/libc  -Wl,-melf_x86_64 -L $dirname \
 -L /usr/lib/gcc/x86_64-*linux-gnu/6.* -Wl,crt0.o -Wl,--build-id=none $* -lc -lgcc
